import gradio as gr
import pandas as pd

# --------------------------------------------------
# Load precomputed prediction table
# --------------------------------------------------
CSV_PATH = (
    "student_seq_alpha0.3esm2_t6_8M_UR50D_beta0.7_T4.0_best.pt."
    "distilled_student_predictions.csv"
)

df = pd.read_csv(CSV_PATH)

# Normalize sequences for lookup
df["sequence"] = df["sequence"].astype(str).str.upper().str.strip()

lookup = {
    seq: {
        "True Label": int(label),
        "Teacher Logit": round(float(t_logit), 4),
        "Student Logit": round(float(s_logit), 4),
        "BECR Probability": round(float(prob), 4),
        "Prediction": "Positive" if int(pred) == 1 else "Negative"
    }
    for seq, label, t_logit, s_logit, prob, pred in zip(
        df["sequence"],
        df["label"],
        df["teacher_logit"],
        df["student_logit"],
        df["student_prob"],
        df["student_pred"]
    )
}


# --------------------------------------------------
# Prediction function
# --------------------------------------------------
def predict(sequence):
    sequence = sequence.strip().upper()

    if len(sequence) == 0:
        return {
            "Error": "Please input a protein sequence."
        }

    if sequence not in lookup:
        return {
            "Error": (
                "Sequence not found in precomputed prediction table. "
                "This demo currently only supports sequences contained in "
                "the uploaded CSV file."
            )
        }

    return lookup[sequence]


# --------------------------------------------------
# Example sequences
# --------------------------------------------------
examples = [[seq] for seq in df["sequence"].head(10).tolist()]


# --------------------------------------------------
# Gradio interface
# --------------------------------------------------
demo = gr.Interface(
    fn=predict,
    inputs=gr.Textbox(
        lines=8,
        label="Protein Sequence",
        placeholder="Paste a sequence from the prediction CSV..."
    ),
    outputs=gr.JSON(label="Prediction"),
    title="BECR Distilled Student Predictor",
    description=(
        "Lookup interface for precomputed predictions generated by the "
        "distilled ESM2 student model."
    ),
    examples=examples
)

demo.launch(server_name="0.0.0.0", server_port=8080)